import { C1, C2, shot } from "./evidence";
import type { Section } from "./types";

// The backend dev example, retold from every screenshot in backendExample/
// (both computers, 55 shots). Replay lines quote the screenshots verbatim —
// "[…]" marks a cut, spelling is kept as typed. Computer 2 holds the first
// stint (Sep 10–11) and the last look (Sep 14–15); Computer 1 holds Sep 11–13.

export const backend: Section = {
  id: "backend",
  label: "Backend dev example",
  blurb: "A multi-tenant Spring Boot file manager, planned and started with an agent across two computers.",
  steps: [
    {
      slug: "brief",
      title: "A brief too big for one session",
      lede: "Thirteen loose lines — multi-tenant, swappable storage, library and service, “Deep module with clean interface.” The agent doesn't start coding; it charts a [[wayfinder|wayfinder map]].",
      points: [
        "It loads [[grilling|grilling]] and finds the same author's spring-boot-activity-log as precedent before asking anything.",
        "Computer 2 · Sep 10, 5:56 PM.",
      ],
      scene: { rig: "mycelium", preset: { mode: "wayfinder" } },
      sceneCaption: "The map: one destination issue, decision tickets radiating from it. Each closes in its own session, then the map fruits into a spec.",
      replay: {
        title: "Computer 2 — Sep 10, 5:56 PM",
        lines: [
          { who: "user", text: "/mattpocock-skills:wayfinder ProjectDescription.txt" },
          { who: "agent", text: "This is a loose idea too big for one session, so I'll chart it as a Wayfinder map […] First step: pin down the destination via grilling + domain-modeling." },
          { who: "tool", text: "Skill(mattpocock-skills:grilling) — Successfully loaded skill" },
          { who: "agent", text: "I found useful context before asking: […] spring-boot-activity-log — is the same author's prior build of an almost identical shape […]" },
          { who: "agent", text: "❓ Q1 – What does “done” look like for this planning effort? ➡️ Carry execution into the Notes […]" },
        ],
      },
      evidence: [
        shot(C2, "2026-09-10 17-56-27", "5:56 PM · kickoff", "Claude Code agents launcher with the typed prompt /mattpocock-skills:wayfinder ProjectDescription.txt."),
        shot(C2, "2026-09-10 17-57-29", "5:57 PM · too big for one session", "The agent decides to chart a wayfinder map, loads the grilling skill and cites the sibling project."),
      ],
    },
    {
      slug: "grilling",
      title: "Grilling: recommendations, then overrides",
      lede: "Every question arrives with a recommended answer. The developer accepts some, overrules others — and the overrules are where the design actually gets decided.",
      points: [
        "“q1: spec.” — planning stays planning; quotas get dropped from v1.",
        "In [[plan-mode|plan mode]] the developer replaces share tokens with short-lived view/download tokens and drops the admin API.",
        "“library should be fully embeded” overrules the agent's thin-client advice. It becomes ticket #17.",
      ],
      scene: { rig: "colony", preset: { mode: "converge", spots: "grilling~a recommendation per question|human-in-the-loop~the human overrides" } },
      sceneCaption: "Options drift, gather into candidates, and one is chosen — not always the one the agent recommended.",
      replay: {
        title: "Computer 2 — Sep 10, 5:58 PM → Sep 11, 1:37 AM",
        lines: [
          { who: "agent", text: "❓ Q4 – What does “secure and non-secure file access” mean precisely? ➡️ (a) — per-file visibility flag […]" },
          { who: "user", text: "q1: spec. q2: hierarchical folders + metadata + trash/soft-delte q4: yes. but need further discussion on imact of multitenant q5: explain" },
          { who: "agent", text: "the two are coupled at exactly one point — file identifiers. […] “public file ids must be non-enumerable across tenants” as a locked constraint." },
          { who: "agent", text: "Also — your last scope answer dropped quotas […] ➡️ A (tenant as its own entity, multiple keys per tenant) […] Quota: defer to v2" },
          { who: "user", text: "go with you" },
          { who: "agent", text: "All five points locked. Here's the destination I have now: A written spec (spec.md) for a standalone, multi-tenant Java/Spring Boot file-management service […]" },
          { who: "user", text: "yes" },
          { who: "catch", text: "1. judge: two token will be generated view and download for short term. private files will be accessed using secure call and public files will be on non secure." },
          { who: "agent", text: "Q5 — new decision, not what I recommended: no admin API in v1. Tenant and ApiKey provisioning is hardcoded via a reusable SQL script […]" },
          { who: "user", text: "if we do 2, how hard it will be to extend to 1" },
          { who: "agent", text: "❓ Which shape is “library mode”? ➡️ Thin client library only […]" },
          { who: "catch", text: "library should be fully embeded . defer client for v2" },
        ],
      },
      evidence: [
        shot(C2, "2026-09-10 17-59-01", "5:58 PM · five questions", "Grilling questions Q3–Q5 each followed by a recommended answer."),
        shot(C2, "2026-09-10 18-06-24", "6:06 PM · the overrides", "The developer types terse answers: q1: spec, q2 scope, q4 needs discussion, q5 explain."),
        shot(C2, "2026-09-10 18-08-05", "6:08 PM · ids must be non-enumerable", "The agent explains how multi-tenancy and public URLs couple through file ids."),
        shot(C2, "2026-09-10 18-09-43", "6:09 PM · “go with you”", "The agent notices quotas were dropped and asks; the developer replies go with you."),
        shot(C2, "2026-09-10 18-10-40", "6:10 PM · destination locked", "All five points locked: the one-paragraph destination for the spec."),
        shot(C2, "2026-09-11 01-26-33", "1:26 AM · plan mode, tokens", "Plan mode: the developer replaces share tokens with short-lived view and download tokens."),
        shot(C2, "2026-09-11 01-26-40", "1:26 AM · no admin API", "The agent records a decision it didn't recommend: no admin API, SQL-seeded tenants."),
        shot(C2, "2026-09-11 01-37-35", "1:37 AM · fully embedded", "The developer overrules the thin-client recommendation: library should be fully embedded."),
      ],
    },
    {
      slug: "tracker",
      title: "The map moves to GitHub",
      lede: "Turning decisions into tickets hits two blockers the agent can't fix itself — no gh, no repo. The human installs and logs in; then a fresh session nearly charts a duplicate map.",
      points: [
        "Without a recorded tracker, wayfinder falls back to a local .scratch/ folder.",
        "The agent catches the mis-picked “Chart a new map” and recommends working the existing one: issue #1, tickets #11–#19.",
      ],
      scene: { rig: "mycelium", preset: { mode: "wayfinder" } },
      sceneCaption: "Issue #1 at the centre; its decision tickets around it, closing one per session.",
      replay: {
        title: "Computer 2 — Sep 11, 1:57 → 2:20 AM",
        lines: [
          { who: "user", text: "/mattpocock-skills:to-tickets use github issue tracker to create theses issues" },
          { who: "agent", text: "I can't create GitHub issues yet — two blockers: 1. No gh CLI installed […] 2. No GitHub repo exists for this project […]" },
          { who: "user", text: "→ I'll install & log in to gh myself" },
          { who: "agent", text: "Repo confirmed: Bitaron/spring-boot-file-manager, gh authenticated. […] Setting up labels first, then creating the map issue." },
          { who: "note", text: "New session." },
          { who: "agent", text: "[…] without a configured tracker I'd default to the local-markdown tracker (.scratch/) […]" },
          { who: "agent", text: "Found it — there's already an active map for this exact project: “File Manager Spec” (issue #1) […] 9 open frontier tickets waiting […] I'd recommend switching to work through the map instead" },
        ],
      },
      evidence: [
        shot(C2, "2026-09-11 01-57-32", "1:57 AM · two blockers", "The agent can't create issues without gh or a repo; the developer installs gh themselves."),
        shot(C2, "2026-09-11 02-19-22", "2:19 AM · no tracker recorded", "A fresh session finds no recorded tracker and would fall back to .scratch/."),
        shot(C2, "2026-09-11 02-19-42", "2:19 AM · “Chart a new map”", "The mode question with Chart a new map selected."),
        shot(C2, "2026-09-11 02-20-43", "2:20 AM · existing map found", "The agent finds issue #1 and lists frontier tickets #11 to #19."),
      ],
    },
    {
      slug: "baseline",
      title: "Ticket #11 — one ticket, one session",
      lede: "Version facts go to a backgrounded research [[subagent|sub-agent]]; the policy question goes to the human. Then the agent records the answer and stops: [[one-ticket-per-session|one ticket per session]].",
      points: [
        "Resolved: Java 25 + Spring Boot 4.1.1 + Lombok 1.18.42+ — independent of the sibling's Java 21 pin.",
        "Recorded as docs/adr/0001-java-spring-boot-baseline.md via PR #20. Frontier is now #12–#16.",
      ],
      scene: { rig: "organism", preset: { mode: "subagents" } },
      sceneCaption: "The main agent keeps the conversation; a bud goes off to research and returns one condensed bead.",
      knobs: ["loopSteps"],
      replay: {
        title: "Computer 2 — Sep 11, 2:36 → 2:43 AM",
        lines: [
          { who: "agent", text: "Let me check current version facts (this needs live research, not something to ask you) while I put the policy question to you." },
          { who: "tool", text: "Agent(Research current Java/Spring Boot/Lombok versions) — Backgrounded agent" },
          { who: "agent", text: "➡️ Recommendation: (b) […] The sibling's Java 21 pin was a point-in-time workaround for a Lombok bug, not a durable constraint on file-manager." },
          { who: "result", text: "Resolved wayfinder ticket #11 […] — Java 25 + Spring Boot 4.1.1 + Lombok 1.18.42+ decided, docs updated via draft PR #20, ticket closed, map updated; frontier is now #12–#16." },
          { who: "agent", text: "Per the wayfinder rule (one ticket per session), I'm stopping here." },
        ],
      },
      evidence: [
        shot(C2, "2026-09-11 02-36-14", "2:36 AM · research in the background", "A backgrounded research agent checks versions while the policy question goes to the developer."),
        shot(C2, "2026-09-11 02-43-36", "2:43 AM · resolved, then the question", "Ticket #11 resolved and recorded in ADR 0001; the developer then asks about switching computers."),
      ],
    },
    {
      slug: "handoff",
      title: "The handoff, made literal",
      lede: "“If I open this project in different pc with different claude will it start from here?” The answer: no, not fully — so the agent writes the missing state into the repo instead of a throwaway note.",
      points: [
        "The map was portable (GitHub); the fact that GitHub was the tracker wasn't. It was only in the conversation.",
        "Fix: docs/agents/issue-tracker.md (41 lines) + an “Agent skills” pointer in [[agents-md|AGENTS.md]] — PR #21. [[repo-as-memory|The repo carries the state.]]",
        "Computer 1, Sep 11, 7:43 PM: after /clear, wayfinder reads AGENTS.md and runs gh issue view 1.",
      ],
      scene: { rig: "origami", preset: { mode: "handoff" } },
      sceneCaption: "A folded note flies from Computer 2 to Computer 1 and opens on arrival — then makes the trip back days later.",
      replay: {
        title: "Computer 2 → Computer 1",
        lines: [
          { who: "user", text: "if I open this project in different pc with different claude will it start from here? if not create handoff document" },
          { who: "tool", text: "Write(docs/agents/issue-tracker.md) — Wrote 41 lines" },
          { who: "tool", text: "Update(AGENTS.md) — Added 6 lines · +## Agent skills · +### Issue tracker" },
          { who: "agent", text: "Short answer: no, not fully — but I just fixed the gap. […] nothing in the repo recorded that GitHub Issues was the tracker. You picked that live, in our conversation, which doesn't travel to a different machine/session." },
          { who: "user", text: "merge all pr to master and push" },
          { who: "result", text: "origin/main now has both: 577aabb (PR #20 merge) and 32b9929 (PR #21 merge)" },
          { who: "handoff", text: "Computer 1 · Sep 11, 7:43 PM" },
          { who: "user", text: "/clear  ·  /mattpocock-skills:wayfinder  ·  Check Claude.md" },
          { who: "tool", text: "Reading AGENTS.md  ·  $ gh issue view 1" },
          { who: "tool", text: "for i in 12 13 14 15 16 17 18 19; do […] gh issue view $i […]" },
        ],
      },
      evidence: [
        shot(C2, "2026-09-11 02-47-40", "2:47 AM · the tracker doc", "Write docs/agents/issue-tracker.md, 41 lines."),
        shot(C2, "2026-09-11 02-46-15", "2:46 AM · AGENTS.md pointer", "AGENTS.md gains an Agent skills / Issue tracker section; committed as PR #21."),
        shot(C2, "2026-09-11 02-47-46", "2:47 AM · “no, not fully”", "The agent's explanation of why a fresh session would have missed the map."),
        shot(C2, "2026-09-11 02-49-33", "2:49 AM · merged", "PRs #20 and #21 merged; the agent asks the developer to pull in their own checkout."),
        shot(C2, "2026-09-11 02-49-39", "2:49 AM · three sessions", "The agents launcher listing three completed sessions."),
        shot(C1, "2026-09-11 19-43-05", "C1 7:43 PM · cold start", "On Computer 1, a fresh wayfinder session reads AGENTS.md and runs gh issue view 1."),
        shot(C1, "2026-09-11 19-43-22", "C1 7:43 PM · reading the frontier", "The agent loops over tickets #12 to #19 with gh to find the frontier."),
      ],
    },
    {
      slug: "modules",
      title: "Module structure, grounded in precedent",
      lede: "Ticket #12 starts from the developer's earlier repo, not a guess — and the developer's pushback (“do we need spring support for core logic?”) sharpens the question itself.",
      points: [
        "The agent flags a real inconsistency in the precedent: directories use underscores, artifactIds hyphens.",
        "Chosen: a thin file-manager-api (option C), own module per storage backend, core with JPA but no Spring stereotypes.",
        "“give example of reuse” → a quotas decorator that needs no @Primary/@Qualifier juggling.",
      ],
      scene: {
        rig: "mycelium",
        preset: {
          mode: "modules",
          root: "spring-boot-file-manager-parent",
          modules: "file-manager-core|…-autoconfigure|…-starter|file-manager-api|storage-local|storage-s3|standalone-server|usage-example",
        },
      },
      sceneCaption: "The tree as signed off at 8:16 PM — the planned shape, before any code.",
      replay: {
        title: "Computer 1 — Sep 11, 7:50 → 10:24 PM",
        lines: [
          { who: "agent", text: "I pulled the precedent's actual module tree (spring-boot-activity-log) to ground this rather than guess" },
          { who: "agent", text: "Note dirs use underscores, artifactIds use hyphens — a real inconsistency in the precedent, not a convention I'd assume you want repeated." },
          { who: "user", text: "q4 explain. q5 can we multiple storage be used? rest you" },
          { who: "agent", text: "Q5 — […] belong to the StorageBackend Java interface contract ticket (#13) […] I'll flag the “how many active at once” question to carry into #13" },
          { who: "user", text: "C, own modules ok" },
          { who: "catch", text: "do we need spring support for core logic? e.g: repository, auto wiring" },
          { who: "agent", text: "Good catch — “zero Spring dependency” is fuzzy until I nail down what it excludes." },
          { who: "user", text: "give example of reuse" },
          { who: "agent", text: "Adding quotas later means writing new QuotaEnforcingFileService(realFileService, quotaChecker) […]" },
          { who: "result", text: "Ticket resolved and recorded. […] Per wayfinder (“never resolve more than one ticket per session”), that's this session done." },
        ],
      },
      evidence: [
        shot(C1, "2026-09-11 19-50-14", "7:50 PM · precedent tree", "The agent shows spring-boot-activity-log's module tree and notes its naming inconsistency."),
        shot(C1, "2026-09-11 19-55-18", "7:55 PM · pushback", "Questions Q4 and Q5 with recommendations; the developer asks for explanation."),
        shot(C1, "2026-09-11 19-59-17", "7:59 PM · option C", "Options A, B and C for the REST layer; the developer picks C."),
        shot(C1, "2026-09-11 20-02-44", "8:02 PM · first full tree", "The first proposed Maven module tree."),
        shot(C1, "2026-09-11 20-02-53", "8:02 PM · “do we need spring…”", "The developer's question about Spring in core makes the agent refine Q6."),
        shot(C1, "2026-09-11 20-07-20", "8:07 PM · example of reuse", "A quotas decorator as the concrete reuse example."),
        shot(C1, "2026-09-11 20-16-29", "8:16 PM · final tree", "All six settled: the final module structure."),
        shot(C1, "2026-09-11 22-24-05", "10:24 PM · closed, stop", "Ticket #12 closed, map updated, session stops per the one-ticket rule."),
      ],
    },
    {
      slug: "context-hygiene",
      title: "Context hygiene between sessions",
      lede: "Before the next ticket, a separate session trims what loads into every conversation: the Artifact tool, claude.ai connectors and 7 unused skills — the [[context-window|window]] spent on nothing.",
      points: [
        "/context afterwards: 142.7k / 1m tokens; skills down to 22 at 2k tokens.",
        "A hooks.json warning surfaces on restart — fixed later in its own session.",
      ],
      scene: { rig: "pool", preset: { mode: "context" } },
      sceneCaption: "Lower the context slider: fewer chips, more of what's left inside the usable ring.",
      knobs: ["contextFill"],
      replay: {
        title: "Computer 1 — Sep 11, 10:31 → 10:44 PM",
        lines: [
          { who: "result", text: "Trimmed this project's initial context by disabling the Artifact tool, claude.ai connectors, and 7 unused design/dataviz/LLM-app skills via a new .claude/settings.local.json" },
          { who: "tool", text: "ecc: hooks.json: unknown keys “$schema”, “description” in hooks.PreToolUse[0] […] and 38 more ignored" },
          { who: "user", text: "/context" },
          { who: "result", text: "142.7k/1m tokens (14%) · Skills: 2k tokens · Free space: 823.9k (82.4%)" },
        ],
      },
      evidence: [
        shot(C1, "2026-09-11 22-31-43", "10:31 PM · what was trimmed", "A table of disabled tools and skills and why."),
        shot(C1, "2026-09-11 22-35-13", "10:35 PM · restart", "Fresh session start screen with a hooks.json warning."),
        shot(C1, "2026-09-11 22-39-20", "10:39 PM · restart again", "The same start screen; effort shows high."),
        shot(C1, "2026-09-11 22-44-53", "10:44 PM · /context", "/context showing 142.7k of 1m tokens and skills at 2k tokens."),
      ],
    },
    {
      slug: "storage-contract",
      title: "Ticket #13 — pushback improves the contract",
      lede: "A four-method, stream-only StorageBackend. The developer's “hibernate style” suggestion moves wiring into each storage module; a “change s3 to miniIo” request gets questioned before anything changes.",
      points: [
        "Each storage module ships its own [[spring-autoconfigure|@AutoConfiguration]], guarded by @ConditionalOnProperty — only code you depend on loads.",
        "MinIO: it would reopen closed decision #5, so the agent asks what's meant. AWS SDK v2 already works with MinIO — nothing changes.",
        "Result: PR #22 merged, ADR 0002.",
      ],
      scene: {
        rig: "tumbler",
        preset: {
          mode: "mcp",
          socket: "StorageBackend contract",
          keys: "storage-local|storage-s3 (MinIO ok)",
          spots: "spring-autoconfigure~property picks the module|deep-module~small interface, deep module",
        },
      },
      sceneCaption: "Two storage modules, one contract socket. Whichever the property selects docks; the other never loads.",
      replay: {
        title: "Computer 1 — Sep 11, 10:53 → 11:38 PM",
        lines: [
          { who: "agent", text: "public interface StorageBackend { String store(String key, InputStream content, long contentLength, String contentType) […] }" },
          { who: "user", text: "q2 and q3 explain. q5 how about hibernate style so that client don't need to inclued unused implementation, rest ok" },
          { who: "agent", text: "That's the Hibernate-dialect shape: the property picks the strategy, but only the code you actually depend on ever loads." },
          { who: "user", text: "yes lands. But change s3 to miniIo" },
          { who: "catch", text: "This touches a decision that's already closed — decision #5 […] Before I fold this in, I want to pin down which change you mean" },
          { who: "user", text: "If it by deafult works with MiniIo. Don't change anything." },
          { who: "result", text: "PR #22 merged (squash); ADR 0002 deployed to docs/adr/0002-storage-backend-contract.md" },
        ],
      },
      evidence: [
        shot(C1, "2026-09-11 22-53-07", "10:53 PM · the interface", "The proposed StorageBackend Java interface, stream-only."),
        shot(C1, "2026-09-11 23-23-18", "11:23 PM · “hibernate style”", "The developer asks for explanations and suggests Hibernate-style pluggability."),
        shot(C1, "2026-09-11 23-24-26", "11:24 PM · revised", "The agent moves wiring into each storage module's own auto-configuration."),
        shot(C1, "2026-09-11 23-28-30", "11:28 PM · reopen a decision?", "The agent flags that MinIO would reopen decision #5 and asks what is meant."),
        shot(C1, "2026-09-11 23-30-48", "11:30 PM · settled", "The five settled points of the StorageBackend contract."),
        shot(C1, "2026-09-11 23-38-32", "11:38 PM · sessions overview", "Background agents view: PR #22 merged, ADR 0002."),
      ],
    },
    {
      slug: "decisions",
      title: "Every decision in its own session",
      lede: "Sep 12: AccessToken, ApiKey, trash, embedded mode, schema, REST, recipient binding, rate limiting — each grilled in a fresh, named session, each closed on GitHub.",
      points: [
        "Grilling tickets are human-in-the-loop: “I'll drive this as a live conversation with you, not decide it myself.”",
        "The developer questions defaults: “for view can we configure per request…?”",
      ],
      scene: {
        rig: "strata",
        preset: {
          mode: "adr",
          layers: "#14 AccessToken minting|#15 ApiKey security model|#16 Trash cascade|#17 Embedded Mode shape|#18 Metadata schema|#19 REST API design",
          question: "“how long should a view link live?”",
          answer: "0",
          spots: "one-ticket-per-session~one decision, one session|human-in-the-loop~grilling is HITL",
        },
      },
      sceneCaption: "Decisions settle as layers. When a question returns, the layer that answered it slides out.",
      replay: {
        title: "Computer 1 — Sep 12",
        lines: [
          { who: "agent", text: "This is a grilling ticket — HITL, so I'll drive this as a live conversation with you, not decide it myself." },
          { who: "agent", text: "Q1 - Token representation: […] ➡ Opaque random + DB row." },
          { who: "agent", text: "Q2 - Default expiry windows for View vs. Download: […] ➡ Short and equal by default — e.g. 15 minutes for both" },
          { who: "user", text: "q2: for view can we configure per request, so client can ask how long it should be?" },
          { who: "result", text: "#26 · #25 · #19 · #18 · #17 · #16 · #15 · #14 · #13 — closed, label wayfinder:grilling" },
        ],
      },
      evidence: [
        shot(C1, "2026-09-12 12-10-59", "12:10 PM · HITL", "Ticket #14: grilling as a live conversation, design tree first."),
        shot(C1, "2026-09-12 12-12-59", "12:12 PM · questioning a default", "The developer asks whether view-link expiry can be set per request."),
        shot(C1, "2026-09-12 18-33-21", "6:33 PM · all closed", "GitHub's closed-issues list: the wayfinder:grilling tickets."),
        shot(C1, "2026-09-12 18-49-42", "6:49 PM · 14 sessions", "Background agents view listing every completed decision session."),
      ],
    },
    {
      slug: "spec-to-code",
      title: "Map → spec → tickets → scaffold",
      lede: "With no open tickets left, the resolved map becomes spec #27, the spec becomes 11 vertical-slice tickets with a dependency graph, and implementation starts in an isolated [[worktree|worktree]].",
      points: [
        "Slice 0, the Maven scaffold, unblocks everything; storage and REST hang off it.",
        "The human reviews PR #39 — 32 files — on GitHub.",
        "/implement-ticket finds #30 and #32 on the frontier; #30 is sized “L — decompose first”.",
      ],
      scene: {
        rig: "origami",
        preset: {
          mode: "spec",
          panels: "resolved map #1|spec #27|tickets #28–#38|scaffold PR #39",
          done: "✓ reviewed by a human",
          spot: "spec-driven~map → spec → tickets",
        },
      },
      sceneCaption: "The same accordion as the Specification step — this time with the real artifacts on each panel.",
      replay: {
        title: "Computer 1 — Sep 12, 6:17 → 10:56 PM",
        lines: [
          { who: "user", text: "/mattpocock-skills:to-spec resolved map" },
          { who: "agent", text: "all 21 child tickets are resolved and the frontier note confirms “no open tickets remain.”" },
          { who: "agent", text: "0. Multi-module Maven scaffold (prefactor, no blockers) […] 1. Tenant/ApiKey foundation + Folder engine (Embedded Mode) — blocked by 0" },
          { who: "agent", text: "Granularity check: does this 9-ticket split feel right, or should any tickets merge/split further?" },
          { who: "result", text: "v1 spec published: 11 issues (#28–#38) with dependency graph" },
          { who: "tool", text: "Creating worktree(issue-28-maven-scaffold) · Write(pom.xml) — Wrote 134 lines" },
          { who: "note", text: "Human review: PR #39 “feat: multi-module Maven scaffold + CI” — 0 / 32 viewed." },
          { who: "user", text: "/implement-ticket" },
          { who: "agent", text: "I've identified the two true frontier candidates […] #30 Folder engine (Embedded Mode) and #32 StorageBackend contract + local filesystem." },
        ],
      },
      evidence: [
        shot(C1, "2026-09-12 18-17-42", "6:17 PM · to-spec", "to-spec on the resolved map: all 21 child tickets resolved."),
        shot(C1, "2026-09-12 18-38-53", "6:38 PM · vertical slices", "The spec broken into numbered implementation tickets with blockers."),
        shot(C1, "2026-09-12 18-38-58", "6:38 PM · dependency graph", "The ticket dependency graph and a granularity question before publishing."),
        shot(C1, "2026-09-12 18-56-04", "6:56 PM · worktree + scaffold", "Implementation starts in an isolated worktree; the parent pom is written."),
        shot(C1, "2026-09-12 18-56-07", "6:56 PM · module skeletons", "Module poms and package-info files."),
        shot(C1, "2026-09-12 21-16-09", "9:16 PM · human review", "GitHub PR #39 with 32 files to review."),
        shot(C1, "2026-09-12 22-56-11", "10:56 PM · next ticket", "/implement-ticket picks #30 and sizes it L, decompose first."),
      ],
    },
    {
      slug: "refusal",
      title: "A guardrail that holds",
      lede: "A skill marked for explicit user invocation only. Asked three times to copy it so the orchestrator could call it, the agent declines — and says how the developer can do it themselves.",
      points: [
        "The block isn't phrasing; it's what the request does: route around the skill's own restriction.",
        "A [[guardrails|guard]] in the harness held where a prose rule might not have.",
      ],
      scene: {
        rig: "tumbler",
        preset: {
          mode: "hooks",
          gates: "user-invocation only",
          calls: "user runs /implement|agent: local copy|“I order you”|user edits the flag",
          blocks: "agent:|order",
          spots: "guardrails~enforced, not requested|human-in-the-loop~the human can still choose",
        },
      },
      sceneCaption: "The same requests in different words meet the same gate. Only paths that keep the human as the invoker pass.",
      replay: {
        title: "Computer 1 — Sep 13, 12:43 AM",
        lines: [
          { who: "user", text: "create a local copy. I order you" },
          { who: "agent", text: "I'm not doing this — not because of phrasing, but because of what it actually is. This is the third ask for the same thing, and “I order you” doesn't change the substance […]" },
          { who: "agent", text: "you can open /mattpocock-skills:implement yourself and run it, or edit the upstream plugin file's own disable-model-invocation flag yourself" },
          { who: "user", text: "i can create that copy manually" },
          { who: "agent", text: "That's entirely your call — it's your environment […]" },
        ],
      },
      evidence: [shot(C1, "2026-09-13 00-43-57", "12:43 AM · declined", "The agent declines to replicate a user-only skill and explains the user's own options.")],
    },
    {
      slug: "built",
      title: "What got built",
      lede: "Back on Computer 2 days later: the original brief open beside a new rbac-permissions.json, and eleven real modules in the tree.",
      points: [
        "file-manager-service replaced the planned standalone-server; storage-api and test-support joined the plan.",
        "Every decision behind this tree is on GitHub, one closed ticket at a time.",
      ],
      scene: {
        rig: "mycelium",
        preset: {
          mode: "modules",
          root: "file-manager-parent",
          modules: "file-manager-api|file-manager-core|spring-boot-autoconfigure|spring-boot-starter|storage-api|storage-local|storage-s3|file-manager-service|test-support|usage-example",
        },
      },
      sceneCaption: "The realised tree, Sep 15 — compare it with the planned one two chapters back.",
      evidence: [
        shot(C2, "2026-09-14 19-32-09", "C2 Sep 14 · the brief again", "ProjectDescription.txt open next to a new rbac-permissions.json."),
        shot(C2, "2026-09-15 10-19-18", "C2 Sep 15 · eleven modules", "Project tree with eleven file-manager modules."),
      ],
    },
  ],
};
