import type { Section } from "./types";

// Same 23 teaching beats as v1's Intro to AI (src/sections.ts), rewritten
// for density. Facts are carried over from v1 and ProjectBrief.md, not added.

export const intro: Section = {
  id: "intro",
  label: "Intro to AI",
  blurb: "From plan-and-hand-off to agents, and the practices that keep them honest.",
  steps: [
    {
      slug: "traditional",
      title: "Traditional software building",
      lede: "Work moves between people in three stages — [[waterfall|plan]], [[work-breakdown|divide]], [[integration|implement]] — and every hand-off is a place context can leak.",
      points: [
        "Planning: requirements, analysis, architecture, the plan itself.",
        "Division: assign responsibilities, coordinate, manage dependencies.",
        "Implementation: inspect the codebase, build, test, debug, review, integrate.",
      ],
      scene: { rig: "colony", preset: { mode: "relay" } },
      sceneCaption: "Workers ferry each piece from the plan cairn to division to implementation. Move the cursor through them — the colony routes around you.",
      knobs: ["temperature"],
    },
    {
      slug: "token-generation",
      title: "Token generation",
      lede: "A model reads everything so far, scores candidate [[token|tokens]], picks one, appends it — and repeats. That's [[next-token|next-token prediction]], and it's all an agent ever does.",
      points: [
        "The context goes in, one token comes out, the token joins the context.",
        "[[temperature|Temperature]] reshapes the odds: low picks the obvious word, high lets long shots through.",
        "Simplified: real tokens are word-pieces and every token in the vocabulary is scored, not five.",
      ],
      scene: { rig: "loom" },
      sceneCaption: "Stalk height is each candidate's probability. Drag temperature up and watch “sings” and “purple” start making it into the sentence.",
      knobs: ["temperature"],
    },
    {
      slug: "stateless",
      title: "Stateless sessions",
      lede: "A session doesn't remember another, independent session. Each starts from whatever context it's given — nothing more. [[stateless|Statelessness]] is the default; [[agent-memory|memory]] is something the application adds.",
      points: [
        "Session A: context → response. Session B: new context → response. No shared memory.",
        "An app can store state and feed it into Session B as context — the model is still stateless.",
      ],
      scene: { rig: "pool", preset: { mode: "stateless" } },
      sceneCaption: "Each pool is one session; when it ends it drains completely. Every other pair of sessions the memory basin switches on and carries a few chips across.",
    },
    {
      slug: "model-categories",
      title: "Model categories & reasoning effort",
      lede: "Capability and [[reasoning-effort|effort]] are two separate dials. Anthropic's family is the reference: Haiku (fast), Sonnet (balanced), Opus (deep reasoning).",
      table: [
        ["Category", "Reference", "Typical role"],
        ["Fast / lightweight", "Haiku", "Fast responses, simple tasks, high throughput"],
        ["Balanced", "Sonnet", "General development, analysis, agentic work"],
        ["Deep reasoning", "Opus", "Architecture, hard debugging, long-horizon work"],
      ],
      points: [
        "Effort ladder: none → low → medium → high → xhigh / max. Higher usually means more thinking, latency and [[reasoning-tokens|tokens]].",
        "Newer Anthropic models use [[adaptive-thinking|adaptive thinking]]: depth depends on effort and on task difficulty.",
      ],
      scene: { rig: "organism", preset: { mode: "trio" } },
      sceneCaption: "Three temperaments: small and quick, balanced, large and deliberate. Effort is the number of thought rings each throws before it acts.",
      knobs: ["effort"],
    },
    {
      slug: "providers",
      title: "Model categories across providers",
      lede: "Other vendors map onto the same idea, but effort names are not a shared standard — the same word doesn't buy the same compute.",
      table: [
        ["Model", "Effort levels"],
        ["GPT-5.6 (Luna / Terra / Sol)", "none · low · medium · high · xhigh · max"],
        ["Grok 4.3", "none · low · medium · high · xhigh"],
        ["Grok 4.5", "low · medium · high · xhigh (default high)"],
        ["DeepSeek V4.1-Flash / V4-Pro", "low · high · max"],
        ["Kimi coding models", "low · high · max"],
      ],
      points: [
        "Same provider + different model + different effort → different reasoning, cost and latency.",
        "Qwen3-Max-Thinking: a flagship reasoning model with extra [[test-time-scaling|test-time scaling]].",
        "These are examples in one ecosystem, not equivalents of Haiku / Sonnet / Opus.",
      ],
      scene: {
        rig: "tumbler",
        preset: {
          mode: "providers",
          dials: "GPT-5.6:0,1,2,3,4,5;Grok 4.3:0,1,2,3,4;Grok 4.5:1,2,3,4;DeepSeek:1,3,5;Kimi:1,3,5",
        },
      },
      sceneCaption: "One effort knob, five dials. Each needle can only rest on a notch its model has — orange means it snapped to the nearest one.",
      knobs: ["effort"],
    },
    {
      slug: "token-economics",
      title: "Reasoning effort & token consumption",
      lede: "Higher effort isn't just “smarter”: it spends [[reasoning-tokens|reasoning tokens]], which count as output even though you never see them.",
      points: [
        "Total = input (system prompt, request, context, tool results) + output (answer + thinking).",
        "No fixed multiplier — the count depends on model, task, context, effort, tools and loop length.",
        "Agents re-read their context every step: [[token-multiplication|token multiplication]].",
      ],
      scene: { rig: "loom", preset: { mode: "reasoning" } },
      sceneCaption: "Dark tiles are thinking; light tiles are the visible answer. Raise effort — the sentence stays the same length, the thinking count doesn't.",
      knobs: ["effort", "temperature"],
    },
    {
      slug: "model-selection",
      title: "Model selection as an engineering trade-off",
      lede: "Use the [[model-selection|least model that reliably solves the task]]; step up capability or effort only when the task demands it.",
      points: [
        "Inputs: complexity, reasoning needed, [[latency|latency]], tokens, cost, tool use, context size, reliability.",
        "Simple task → fast / low. Implementation → balanced / medium–high. Architecture → deep / high–max.",
      ],
      scene: { rig: "mobile" },
      sceneCaption: "The task hangs left; your model — with its cost and latency — hangs right. Tasks rotate every few seconds: rebalance with the effort knob.",
      knobs: ["effort"],
    },
    {
      slug: "prompt",
      title: "Prompt",
      lede: "The model has no access to what you meant — only to what you wrote. A [[prompt|prompt]] that names target, condition and expected behaviour flies true.",
      points: [
        "Vague: “Fix the bug.” Which bug? Which file? What counts as fixed?",
        "Specific: “In UserService, fix the crash when a user signs up without an email — return a validation error instead of throwing.”",
        "The difference isn't the model; it's what the model was given.",
      ],
      scene: { rig: "origami", preset: { mode: "prompt" } },
      sceneCaption: "The vague prompt folds into a plane that wanders and lands wide. The specific one lands in the ring.",
    },
    {
      slug: "context-window",
      title: "Context window",
      lede: "The [[context-window|context window]] is the spec-sheet maximum. Usable context is smaller — and it shrinks as noise piles in.",
      points: [
        "Useful, relevant-but-expensive and noisy context all occupy the same window.",
        "Long contexts thin out in the middle — [[lost-in-the-middle|lost in the middle]] — and quality slides before the rim: [[context-rot|context rot]].",
        "No universal number: usable context depends on model, task and how the workflow manages it — [[context-engineering|context engineering]].",
      ],
      scene: { rig: "pool", preset: { mode: "context" } },
      sceneCaption: "Each token is a drop. Pour with the context slider: the middle fades, and past the green ring chips turn orange.",
      knobs: ["contextFill"],
    },
    {
      slug: "agents",
      title: "Agents",
      lede: "A prompt answers once. An agent loops: reason, [[tool-use|use a tool]], observe, reason again — the [[agent-loop|agent loop]] (research calls it [[react|ReAct]]).",
      points: [
        "Goal → reason → act → observe → reason again → continue.",
        "“Continue” doesn't mean done; it means the loop goes round again.",
      ],
      scene: { rig: "organism", preset: { mode: "agent" } },
      sceneCaption: "Think (rings), reach for a tool, observe (the droplet climbs back). The bead ring is tokens: it thickens every lap. The creature follows your cursor.",
      knobs: ["loopSteps", "effort"],
    },
    {
      slug: "sub-agents",
      title: "Sub-agents",
      lede: "A main agent can hand focused work to [[subagent|sub-agents]] — research, architecture, implementation, testing — each with its own, smaller context.",
      points: [
        "Smaller, focused context per sub-agent; work runs in parallel.",
        "The parent stays free to coordinate and only takes back a summary.",
        "Each piece is easier to review and verify on its own.",
      ],
      scene: { rig: "organism", preset: { mode: "subagents" } },
      sceneCaption: "Three buds loop on their own tools. Each returns one bead to the parent — its ring stays thin while theirs churn.",
      knobs: ["loopSteps"],
    },
    {
      slug: "skills",
      title: "Skills",
      lede: "A [[skill|skill]] packages a workflow worth naming once. Only its name and description sit in context; the rest loads when called — [[progressive-disclosure|progressive disclosure]].",
      points: [
        "grill-with-docs calls two other skills: [[grilling|grilling]] and [[domain-modeling|domain-modeling]].",
        "Those produced this site's design brief and its CONTEXT.md glossary.",
        "Adapted from mattpocock/skills; see also anthropics/skills.",
      ],
      scene: { rig: "origami", preset: { mode: "skills" } },
      sceneCaption: "Sealed envelopes show only their name tab. Point at one to call it — grill-with-docs opens two more.",
    },
    {
      slug: "hooks",
      title: "Hooks",
      lede: "A [[hooks|hook]] is a shell command the harness runs on an event — before a tool, after an edit, at session end — without the model being asked.",
      table: [
        ["Event", "Matches", "Action"],
        ["PreToolUse", "Bash", "Block the command"],
        ["PostToolUse", "Edit / Write", "Run a formatter"],
        ["Stop", "session end", "Run the test suite"],
      ],
      scene: { rig: "tumbler", preset: { mode: "hooks" } },
      sceneCaption: "Each tool call passes PreToolUse, the tool, then PostToolUse. The dangerous one is turned back — every time, by the same rule.",
    },
    {
      slug: "agentic-loop",
      title: "Agentic loop",
      lede: "One-shot: prompt → code → done, right first time or not at all. Agentic: plan → act → observe → evaluate → correct → continue, until the goal is met.",
      points: [
        "Observation is what makes correction possible.",
        "More laps → more tokens: watch the ring grow as you add loop steps.",
      ],
      scene: { rig: "organism", preset: { mode: "agent", tools: "Read,Edit,Bash: test,Grep" } },
      sceneCaption: "Set the loop steps and watch the agent lap its tools before an answer (green) surfaces.",
      knobs: ["loopSteps", "effort"],
    },
    {
      slug: "graph",
      title: "Graph",
      lede: "Real workflows branch and depend on each other. A [[workflow-graph|graph]] of states and decisions makes that explicit.",
      points: [
        "Write code → run tests → pass? Yes → done. No → fix.",
        "Fix has a [[dependency-edge|dependency]] on re-running the tests: it isn't finished until they run again.",
      ],
      scene: { rig: "mycelium", preset: { mode: "graph" } },
      sceneCaption: "A pulse walks the graph: it fails twice through fix → re-test before it reaches done.",
    },
    {
      slug: "memory",
      title: "Memory",
      lede: "One interaction remembers nothing; anything that persists lives outside the model. Markdown is the lowest-friction default — not the only option.",
      points: [
        "Markdown files: just text, no structure, querying or built-in collaboration.",
        "Issue trackers (GitHub Issues, Jira) and other stores add structure.",
        "[[beads|Beads]]: a local task/memory manager committed with the repo.",
      ],
      scene: { rig: "strata", preset: { mode: "memory" } },
      sceneCaption: "Hover a stack to recall from it. The loose pile pulls a different sheet each time; the indexed stores pull the right one.",
    },
    {
      slug: "plugins",
      title: "Plugins",
      lede: "A [[plugin|plugin]] bundles skills, commands and hooks so they install once and travel across projects. The skills inside are what actually run.",
      points: [
        "mattpocock-skills on this repo: [[wayfinder|wayfinder]] charted issue #2; grilling + domain-modeling shaped the issue #11 brief.",
        "code-review ran a two-axis review before PR #27; implement turns tickets into shipped steps.",
      ],
      scene: { rig: "origami", preset: { mode: "plugins" } },
      sceneCaption: "The plugin pod opens; the skills it bundles rise out and unfold.",
    },
    {
      slug: "mcp",
      title: "MCP",
      lede: "The [[mcp|Model Context Protocol]] gives agents one standard socket for outside tools and data, so each integration isn't hand-built into the agent.",
      points: [
        "Agent ↔ MCP ↔ external tool or data source; each tool is described by a [[tool-schema|schema]].",
        "Used on this build: [[lazyweb|Lazyweb MCP]] for design references, [[playwright-mcp|Playwright MCP]] for browser testing.",
      ],
      scene: { rig: "tumbler", preset: { mode: "mcp" } },
      sceneCaption: "Different shapes, one shared collar. Each server docks into the same socket in turn.",
    },
    {
      slug: "specification",
      title: "Specification",
      lede: "Turn the idea into a spec that's checked before code exists — catching a wrong idea here is far cheaper than after the build. That's [[spec-driven|spec-driven development]].",
      points: [
        "Idea → /specify (what & why) → /plan and /tasks → implement → verify against the spec.",
        "Verification checks the spec, not whatever the code happens to do.",
      ],
      scene: { rig: "origami", preset: { mode: "spec" } },
      sceneCaption: "The accordion unfolds one panel at a time; only a fully open spec gets the check.",
    },
    {
      slug: "adr",
      title: "ADR — Architecture Decision Records",
      lede: "Record why, not just what, and the same debate doesn't happen twice. Each [[adr|ADR]] names the problem, the alternatives and the consequences.",
      points: [
        "ADR-0002: real per-step URLs on GitHub Pages via a 404.html redirect — hash routing rejected.",
        "Consequence: no router library, consistent with the repo's no-framework stance.",
      ],
      scene: { rig: "strata", preset: { mode: "adr" } },
      sceneCaption: "A returning question drifts in; the decision that already answers it slides out of the stack.",
    },
    {
      slug: "tdd",
      title: "TDD",
      lede: "[[tdd|Test-driven development]] writes the test first: it fails, the minimum implementation makes it pass, then refactor without changing behaviour.",
      points: [
        "Agentic split: one role writes tests, one implements against them, one verifies — an [[independent-verification|independent check]].",
      ],
      scene: { rig: "tumbler", preset: { mode: "tdd" } },
      sceneCaption: "The test ring starts out of line (red). Each attempt turns it closer until work passes (green).",
    },
    {
      slug: "guardrails",
      title: "GuardRails",
      lede: "A [[guardrails|GuardRail]] is enforced by something that runs. A [[soft-rule|rule]] in prose only holds if the agent reads, remembers and follows it.",
      table: [
        ["Kind", "In spring-boot-file-manager"],
        ["Unit test", "core domain rules, no Spring context, fake StorageBackend"],
        ["Integration test", "FileControllerIntegrationTest via Testcontainers"],
        ["Controller test", "AccessTokenControllerTest, standalone MockMvc"],
        ["Architecture test", "illustrative only — ArchUnit isn't in the project"],
      ],
      points: ["A Stop hook running the test suite is a guard, not a rule."],
      scene: { rig: "colony", preset: { mode: "fence" } },
      sceneCaption: "Sloppy work (orange) slips through the dashed rule; the solid guard turns all of it back. Raise temperature to make the work sloppier.",
      knobs: ["temperature"],
    },
    {
      slug: "code-review",
      title: "Code review",
      lede: "AI-written code still gets [[code-review|reviewed]] — correctness, maintainability, security, architecture, requirements, edge cases — on every change, inside the loop.",
      points: ["This site's first three steps were reviewed on two axes, standards and spec, in parallel (PR #27)."],
      scene: { rig: "colony", preset: { mode: "sieve" } },
      sceneCaption: "Flagged work is caught by the review lens and sent back; it returns fixed (green).",
      knobs: ["temperature"],
    },
  ],
};
